spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: ${NAVER_CL_ID}
            client-secret: ${NAVER_CL_SC}
          kakao:
            clientId: ${KAKAO_CL_ID}
          google:
            clientId: ${GOOGLE_CL_ID}
            client-secret: ${GOOGLE_CL_SC}
          facebook:
            clientId: ${FACEBOOK_CL_ID}
            client-secret: ${FACEBOOK_CL_SC}
          instagram:
            clientId: ${INSTA_CL_ID}
            client-secret: ${INSTA_CL_SC}
custom:
  security:
    oauth2:
      client:
        registration:
          naver:
            devUserOauthId: 'oauthId'
          kakao:
            devUserOauthId: 'oauthId'
          google:
            devUserOauthId: 'oauthId'
          facebook:
            devUserOauthId: 'oauthId'