spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/gram__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldj
    password: ${MYSQL_PW}
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CL_ID}
            scope:
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
          google:
            client-id: ${GOOGLE_CL_ID}
            scope:
              - profile
              - email
            client-secret: ${GOOGLE_CL_SC}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          naver:
            client-id: ${NAVER_CL_ID}
            client-secret: ${NAVER_CL_SC}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
            client-name: Naver
          facebook:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-id: ${FACEBOOK_CL_ID}
            client-secret: ${FACEBOOK_CL_SC}
            client-name: Facebook
          instagram:
            provider: instagram
            client-id: ${INSTA_CL_ID}
            client-secret: ${INSTA_CL_SC}
            scope: user_profile, user_media
            client-name: Instagram
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          instagram:
            authorization-uri: https://api.instagram.com/oauth/authorize
            token-uri: https://api.instagram.com/oauth/access_token
            user-info-uri: https://graph.instagram.com/me?fields=id, username&access_token={access-token}
            user-name-attribute: username
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: INFO
    com.ll.gramgram_ai: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
constant:
  max-likeable-person: 10
  modify-delete-cooltime: 180
custom:
  security:
    oauth2:
      client:
        registration:
          naver:
            devUserOauthId: 'DUMMY_NAVER_OAUTH_ID'
          kakao:
            devUserOauthId: 'DUMMY_KAKAO_OAUTH_ID'
          google:
            devUserOauthId: 'DUMMY_GOOGLE_OAUTH_ID'
          facebook:
            devUserOauthId: 'DUMMY_FACEBOOK_OAUTH_ID'